name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x' # Or your preferred/required Node version
          cache: 'npm' # Enable caching for npm dependencies

      - name: Install dependencies
        run: npm ci

      - name: Build ai_licia-client package (Dependency first)
        run: npm run build --workspace=packages/ai_licia-client --if-present

      - name: Build ai_licia-aitum package 
        run: npm run build --workspace=packages/ai_licia-aitum --if-present

      # Optional: Add steps for linting or testing here if needed
      # - name: Run linter
      #   run: npm run lint --workspaces --if-present
      # - name: Run tests
      #   run: npm run test --workspaces --if-present 